flowchart TD

R((R: root))

R --> C1
C1{"c1: Chance<br/>P1 card"}

C1 -->|"Deal: 0 (1/3)"| C2a
C1 -->|"Deal: 1 (1/3)"| C2b
C1 -->|"Deal: 2 (1/3)"| C2c

C2a{"c2: Chance<br/>P2 card | given P1=0"}
C2b{"c3: Chance<br/>P2 card | given P1=1"}
C2c{"c4: Chance<br/>P2 card | given P1=2"}

C2a -->|"Deal: 1 (1/2)"| D01
C2a -->|"Deal: 2 (1/2)"| D02
C2b -->|"Deal: 0 (1/2)"| D10
C2b -->|"Deal: 2 (1/2)"| D12
C2c -->|"Deal: 0 (1/2)"| D20
C2c -->|"Deal: 1 (1/2)"| D21

D01["p1: Player 1, I1<br/>{Pass, Bet}"]
D02["p2: Player 1, I3<br/>{Pass, Bet}"]
D10["p3: Player 1, I1<br/>{Pass, Bet}"]
D12["p4: Player 1, I5<br/>{Pass, Bet}"]
D20["p5: Player 1, I3<br/>{Pass, Bet}"]
D21["p6: Player 1, I5<br/>{Pass, Bet}"]

D01 -->|Pass| P2a1
D01 -->|Bet| P2a2

P2a1["p7: Player 2, I1<br/>{Pass, Bet}"]
P2a2["p8: Player 2, I2<br/>{Pass, Bet}"]

P2a1 -->|Pass| T1
P2a1 -->|Bet| P1resp

P2a2 -->|Pass| T2
P2a2 -->|Bet| T3

P1resp["p9: Player 1, I2<br/>{Pass, Bet}"]

P1resp -->|Pass| T4
P1resp -->|Bet| T5

T1["t1<br/>{-1, 1}"]
T2["t2<br/>{-1, 1}"]
T3["t3<br/>{-2, 2}"]
T4["t4<br/>{1, -1}"]
T5["t5<br/>{-2, 2}"]
