flowchart TD

R((R: root))

R --> C1
C1{"c1: Chance<br/>P1 roll"}

C1 -->|"Roll 1 (1/6)"| C2_1
C1 -->|"Roll 2 (1/6)"| C2_2
C1 -->|"Roll 3 (1/6)"| C2_3
C1 -->|"Roll 4 (1/6)"| C2_4
C1 -->|"Roll 5 (1/6)"| C2_5
C1 -->|"Roll 6 (1/6)"| C2_6

C2_1{"c2: Chance<br/>P2 roll"}
C2_2{"c2: Chance<br/>P2 roll"}
C2_3{"c2: Chance<br/>P2 roll"}
C2_4{"c2: Chance<br/>P2 roll"}
C2_5{"c2: Chance<br/>P2 roll"}
C2_6{"c2: Chance<br/>P2 roll"}

C2_1 -->|"Roll 1 (1/6)"| P1_I1
C2_1 -->|"Roll 2 (1/6)"| P1_I1
C2_1 -->|"Roll 3 (1/6)"| P1_I1
C2_1 -->|"Roll 4 (1/6)"| P1_I1
C2_1 -->|"Roll 5 (1/6)"| P1_I1
C2_1 -->|"Roll 6 (1/6)"| P1_I1

C2_2 -->|"Roll 1 (1/6) "| P1_I1
C2_2 -->|"Roll 2 (1/6)"| P1_I1
C2_2 -->|"Roll 3 (1/6)"| P1_I1
C2_2 -->|"Roll 4 (1/6)"| P1_I1
C2_2 -->|"Roll 5 (1/6)"| P1_I1
C2_2 -->|"Roll 6 (1/6)"| P1_I1

C2_3 -->|"Roll 1 (1/6)"| P1_I1
C2_3 -->|"Roll 2 (1/6)"| P1_I1
C2_3 -->|"Roll 3 (1/6)"| P1_I1
C2_3 -->|"Roll 4 (1/6)"| P1_I1
C2_3 -->|"Roll 5 (1/6)"| P1_I1
C2_3 -->|"Roll 6 (1/6)"| P1_I1

C2_4 -->|"Roll 1 (1/6)"| P1_I1
C2_4 -->|"Roll 2 (1/6)"| P1_I1
C2_4 -->|"Roll 3 (1/6)"| P1_I1
C2_4 -->|"Roll 4 (1/6)"| P1_I1
C2_4 -->|"Roll 5 (1/6)"| P1_I1
C2_4 -->|"Roll 6 (1/6)"| P1_I1

C2_5 -->|"Roll 1 (1/6)"| P1_I1
C2_5 -->|"Roll 2 (1/6)"| P1_I1
C2_5 -->|"Roll 3 (1/6)"| P1_I1
C2_5 -->|"Roll 4 (1/6)"| P1_I1
C2_5 -->|"Roll 5 (1/6)"| P1_I1
C2_5 -->|"Roll 6 (1/6)"| P1_I1

C2_6 -->|"Roll 1 (1/6)"| P1_I1
C2_6 -->|"Roll 2 (1/6)"| P1_I1
C2_6 -->|"Roll 3 (1/6)"| P1_I1
C2_6 -->|"Roll 4 (1/6)"| P1_I1
C2_6 -->|"Roll 5 (1/6)"| P1_I1
C2_6 -->|"Roll 6 (1/6)"| P1_I1

P1_I1["p1: Player 1, I1<br/>{1-1, 1-2, 1-3, 1-4, 1-5, 1-6, 2-1, 2-2, 2-3, 2-4, 2-5, 2-6}"]

P1_I1 -->|"1-1"| P2_I1
P1_I1 -->|"1-2"| P2_I1
P1_I1 -->|"1-3"| P2_I1
P1_I1 -->|"1-4"| P2_I1
P1_I1 -->|"1-5"| P2_I1
P1_I1 -->|"1-6"| P2_I1
P1_I1 -->|"2-1"| P2_I1
P1_I1 -->|"2-2"| P2_I1
P1_I1 -->|"2-3"| P2_I1
P1_I1 -->|"2-4"| P2_I1
P1_I1 -->|"2-5"| P2_I1
P1_I1 -->|"2-6"| P2_I1

P2_I1["p2: Player 2, I1<br/>{1-2, 1-3, 1-4, 1-5, 1-6, 2-1, 2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P2_I1 -->|"1-2"| P1_I2
P2_I1 -->|"1-3"| P1_I2
P2_I1 -->|"1-4"| P1_I2
P2_I1 -->|"1-5"| P1_I2
P2_I1 -->|"1-6"| P1_I2
P2_I1 -->|"2-1"| P1_I2
P2_I1 -->|"2-2"| P1_I2
P2_I1 -->|"2-3"| P1_I2
P2_I1 -->|"2-4"| P1_I2
P2_I1 -->|"2-5"| P1_I2
P2_I1 -->|"2-6"| P1_I2
P2_I1 -->|"Liar"| T1

T1["t1<br/>{1, -1}"]

P1_I2["p3: Player 1, I2<br/>{1-3, 1-4, 1-5, 1-6, 2-1, 2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P1_I2 -->|"1-3"| P2_I2
P1_I2 -->|"1-4"| P2_I2
P1_I2 -->|"1-5"| P2_I2
P1_I2 -->|"1-6"| P2_I2
P1_I2 -->|"2-1"| P2_I2
P1_I2 -->|"2-2"| P2_I2
P1_I2 -->|"2-3"| P2_I2
P1_I2 -->|"2-4"| P2_I2
P1_I2 -->|"2-5"| P2_I2
P1_I2 -->|"2-6"| P2_I2
P1_I2 -->|"Liar"| T2

T2["t2<br/>{-1, 1}"]

P2_I2["p4: Player 2, I2<br/>{1-4, 1-5, 1-6, 2-1, 2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P2_I2 -->|"1-4"| P1_I3
P2_I2 -->|"1-5"| P1_I3
P2_I2 -->|"1-6"| P1_I3
P2_I2 -->|"2-1"| P1_I3
P2_I2 -->|"2-2"| P1_I3
P2_I2 -->|"2-3"| P1_I3
P2_I2 -->|"2-4"| P1_I3
P2_I2 -->|"2-5"| P1_I3
P2_I2 -->|"2-6"| P1_I3
P2_I2 -->|"Liar"| T3

T3["t3<br/>{-1, 1}"]

P1_I3["p5: Player 1, I3<br/>{1-5, 1-6, 2-1, 2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P1_I3 -->|"1-5"| P2_I3
P1_I3 -->|"1-6"| P2_I3
P1_I3 -->|"2-1"| P2_I3
P1_I3 -->|"2-2"| P2_I3
P1_I3 -->|"2-3"| P2_I3
P1_I3 -->|"2-4"| P2_I3
P1_I3 -->|"2-5"| P2_I3
P1_I3 -->|"2-6"| P2_I3
P1_I3 -->|"Liar"| T4

T4["t4<br/>{1, -1}"]

P2_I3["p6: Player 2, I3<br/>{1-6, 2-1, 2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P2_I3 -->|"1-6"| P1_I4
P2_I3 -->|"2-1"| P1_I4
P2_I3 -->|"2-2"| P1_I4
P2_I3 -->|"2-3"| P1_I4
P2_I3 -->|"2-4"| P1_I4
P2_I3 -->|"2-5"| P1_I4
P2_I3 -->|"2-6"| P1_I4
P2_I3 -->|"Liar"| T5

T5["t5<br/>{-1, 1}"]

P1_I4["p7: Player 1, I4<br/>{2-1, 2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P1_I4 -->|"2-1"| P2_I4
P1_I4 -->|"2-2"| P2_I4
P1_I4 -->|"2-3"| P2_I4
P1_I4 -->|"2-4"| P2_I4
P1_I4 -->|"2-5"| P2_I4
P1_I4 -->|"2-6"| P2_I4
P1_I4 -->|"Liar"| T6

T6["t6<br/>{1, -1}"]

P2_I4["p8: Player 2, I4<br/>{2-2, 2-3, 2-4, 2-5, 2-6, Liar}"]

P2_I4 -->|"2-2"| P1_I5
P2_I4 -->|"2-3"| P1_I5
P2_I4 -->|"2-4"| P1_I5
P2_I4 -->|"2-5"| P1_I5
P2_I4 -->|"2-6"| P1_I5
P2_I4 -->|"Liar"| T7

T7["t7<br/>{1, -1}"]

P1_I5["p9: Player 1, I5<br/>{2-3, 2-4, 2-5, 2-6, Liar}"]

P1_I5 -->|"2-3"| P2_I5
P1_I5 -->|"2-4"| P2_I5
P1_I5 -->|"2-5"| P2_I5
P1_I5 -->|"2-6"| P2_I5
P1_I5 -->|"Liar"| T8

T8["t8<br/>{-1, 1}"]

P2_I5["p10: Player 2, I5<br/>{2-4, 2-5, 2-6, Liar}"]

P2_I5 -->|"2-4"| P1_I6
P2_I5 -->|"2-5"| P1_I6
P2_I5 -->|"2-6"| P1_I6
P2_I5 -->|"Liar"| T9

T9["t9<br/>{-1, 1}"]

P1_I6["p11: Player 1, I6<br/>{2-5, 2-6, Liar}"]

P1_I6 -->|"2-5"| P2_I6
P1_I6 -->|"2-6"| P2_I6
P1_I6 -->|"Liar"| T10

T10["t10<br/>{1, -1}"]

P2_I6["p12: Player 2, I6<br/>{2-6, Liar}"]

P2_I6 -->|"2-6"| P1_I7
P2_I6 -->|"Liar"| T11

T11["t11<br/>{1, -1}"]

P1_I7["p13: Player 1, I7<br/>{Liar}"]

P1_I7 -->|"Liar"| T12

T12["t12<br/>{-1, 1}"]
