flowchart TD

R((R: root))

R --> C1
C1{"c1: Chance"}

C1 -->|"d0 (1/2)"| C2
C1 -->|"d1 (1/2)"| C3

C2{"c2: Chance"}
C3{"c3: Chance"}

C2 -->|"d0 (1/2)"| P1_I1
C2 -->|"d1 (1/2)"| P1_I1

C3 -->|"d0 (1/2)"| P1_I2
C3 -->|"d1 (1/2)"| P1_I2

P1_I1["p1: Player 1, I1<br/>{p0a0, p0a1, p0a2}"]
P1_I2["p2: Player 1, I2<br/>{p0a0, p0a1, p0a2}"]

P1_I1 -->|"p0a0"| P2_I1
P1_I1 -->|"p0a1"| P2_I2
P1_I1 -->|"p0a2"| P2_I3

P2_I1["p3: Player 2, I1<br/>{p1a0, p1a1, p1a2}"]
P2_I2["p4: Player 2, I2<br/>{p1a0, p1a1, p1a2}"]
P2_I3["p5: Player 2, I3<br/>{p1a0, p1a1, p1a2}"]

P2_I1 -->|"p1a0"| T1
P2_I1 -->|"p1a1"| T2
P2_I1 -->|"p1a2"| T3

P2_I2 -->|"p1a0"| T4
P2_I2 -->|"p1a1"| T5
P2_I2 -->|"p1a2"| T6

P2_I3 -->|"p1a0"| T7
P2_I3 -->|"p1a1"| T8
P2_I3 -->|"p1a2"| T9

T1["t1<br/>{10, 10}"]
T2["t2<br/>{0, 0}"]
T3["t3<br/>{0, 0}"]

T4["t4<br/>{4, 4}"]
T5["t5<br/>{8, 8}"]
T6["t6<br/>{4, 4}"]

T7["t7<br/>{10, 10}"]
T8["t8<br/>{0, 0}"]
T9["t9<br/>{0, 0}"]

P1_I1 -->|"p0a0"| P2_I4
P1_I1 -->|"p0a1"| P2_I5
P1_I1 -->|"p0a2"| P2_I6

P2_I4["p6: Player 2, I4<br/>{p1a0, p1a1, p1a2}"]
P2_I5["p7: Player 2, I5<br/>{p1a0, p1a1, p1a2}"]
P2_I6["p8: Player 2, I6<br/>{p1a0, p1a1, p1a2}"]

P2_I4 -->|"p1a0"| T10
P2_I4 -->|"p1a1"| T11
P2_I4 -->|"p1a2"| T12

P2_I5 -->|"p1a0"| T13
P2_I5 -->|"p1a1"| T14
P2_I5 -->|"p1a2"| T15

P2_I6 -->|"p1a0"| T16
P2_I6 -->|"p1a1"| T17
P2_I6 -->|"p1a2"| T18

T10["t10<br/>{0, 0}"]
T11["t11<br/>{0, 0}"]
T12["t12<br/>{10, 10}"]

T13["t13<br/>{4, 4}"]
T14["t14<br/>{8, 8}"]
T15["t15<br/>{4, 4}"]

T16["t16<br/>{0, 0}"]
T17["t17<br/>{0, 0}"]
T18["t18<br/>{10, 10}"]

P1_I2 -->|"p0a0"| P2_I1
P1_I2 -->|"p0a1"| P2_I2
P1_I2 -->|"p0a2"| P2_I3

P2_I1 -->|"p1a0"| T19
P2_I1 -->|"p1a1"| T20
P2_I1 -->|"p1a2"| T21

P2_I2 -->|"p1a0"| T22
P2_I2 -->|"p1a1"| T23
P2_I2 -->|"p1a2"| T24

P2_I3 -->|"p1a0"| T25
P2_I3 -->|"p1a1"| T26
P2_I3 -->|"p1a2"| T27

T19["t19<br/>{0, 0}"]
T20["t20<br/>{0, 0}"]
T21["t21<br/>{10, 10}"]

T22["t22<br/>{4, 4}"]
T23["t23<br/>{8, 8}"]
T24["t24<br/>{4, 4}"]

T25["t25<br/>{0, 0}"]
T26["t26<br/>{0, 0}"]
T27["t27<br/>{0, 0}"]

P1_I2 -->|"p0a0"| P2_I4
P1_I2 -->|"p0a1"| P2_I5
P1_I2 -->|"p0a2"| P2_I6

P2_I4 -->|"p1a0"| T28
P2_I4 -->|"p1a1"| T29
P2_I4 -->|"p1a2"| T30

P2_I5 -->|"p1a0"| T31
P2_I5 -->|"p1a1"| T32
P2_I5 -->|"p1a2"| T33

P2_I6 -->|"p1a0"| T34
P2_I6 -->|"p1a1"| T35
P2_I6 -->|"p1a2"| T36

T28["t28<br/>{10, 10}"]
T29["t29<br/>{0, 0}"]
T30["t30<br/>{0, 0}"]

T31["t31<br/>{4, 4}"]
T32["t32<br/>{8, 8}"]
T33["t33<br/>{4, 4}"]

T34["t34<br/>{10, 10}"]
T35["t35<br/>{0, 0}"]
T36["t36<br/>{0, 0}"]
